# fly.toml app configuration file generated for jat-frontend on 2024-10-27T16:21:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jat-frontend'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
